/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import entidades.Calculo;
import entidades.LerCsv;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author default
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblP1 = new javax.swing.JLabel();
        jtfP1 = new javax.swing.JTextField();
        btnP1 = new javax.swing.JButton();
        btnP2 = new javax.swing.JButton();
        jtfP2 = new javax.swing.JTextField();
        lblP2 = new javax.swing.JLabel();
        gerar = new javax.swing.JButton();
        jtfP3 = new javax.swing.JTextField();
        lblP3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblP1.setText("Digite o nome de saída do arquivo");

        jtfP1.setEditable(false);
        jtfP1.setText("Sem arquivo...");
        jtfP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfP1ActionPerformed(evt);
            }
        });

        btnP1.setText("Procurar Arquivo");
        btnP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP1ActionPerformed(evt);
            }
        });

        btnP2.setText("Procurar Arquivo");
        btnP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2ActionPerformed(evt);
            }
        });

        jtfP2.setEditable(false);
        jtfP2.setText("Sem arquivo...");
        jtfP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfP2ActionPerformed(evt);
            }
        });

        lblP2.setText("Selecione o arquivo a ser corrigido");

        gerar.setText("Gerar Notas");
        gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarActionPerformed(evt);
            }
        });

        jtfP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfP3ActionPerformed(evt);
            }
        });

        lblP3.setText("Selecione o arquivo modelo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfP1)
                    .addComponent(jtfP2)
                    .addComponent(jtfP3)
                    .addComponent(gerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnP1)
                            .addComponent(lblP2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnP2)
                            .addComponent(lblP3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblP1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 212, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblP3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnP1)
                .addGap(18, 18, 18)
                .addComponent(lblP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnP2)
                .addGap(18, 18, 18)
                .addComponent(lblP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtfP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gerar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfP1ActionPerformed

    private void btnP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP1ActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.showOpenDialog(lblP1);
        String path1= jfc.getSelectedFile().toString();
        jtfP1.setText(path1);

    }//GEN-LAST:event_btnP1ActionPerformed

    private void btnP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2ActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.showOpenDialog(lblP1);
        String path1= jfc.getSelectedFile().toString();
        jtfP2.setText(path1);
    }//GEN-LAST:event_btnP2ActionPerformed

    private void jtfP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfP2ActionPerformed

    private void gerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarActionPerformed
        if ((jtfP1.getText().equals("Sem arquivo...")) || (jtfP2.getText().equals("Sem arquivo..."))|| (jtfP3.getText().equals(""))){
            System.out.println("Deu errado");
        }else{
            if(jtfP1.getText().equals(jtfP2.getText())){
                System.out.println("Erro! Paths Iguais");
            }else{
               File f = new File(jtfP1.getText());
               File f2 = new File(jtfP2.getText());
               String arquivo = jtfP3.getText();
               String[] certas = LerCsv.receberP1(f);
               String[][] alunos = LerCsv.receberP2(f2);
               Calculo.calcular(certas, alunos, arquivo);
               Object[] options = { "Cadastrar", "Sair" };
               int i =  JOptionPane.showOptionDialog(null, "Cadastrar novo?", "Confirmação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
               if (i == JOptionPane.YES_OPTION){
                    jtfP1.setText("Sem arquivos...");
                    jtfP2.setText("Sem arquivos...");
                    jtfP3.setText("");
               }else{
                   System.exit(0);
               }
               
            }
        }
    }//GEN-LAST:event_gerarActionPerformed

    private void jtfP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfP3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnP1;
    private javax.swing.JButton btnP2;
    private javax.swing.JButton gerar;
    private javax.swing.JTextField jtfP1;
    private javax.swing.JTextField jtfP2;
    private javax.swing.JTextField jtfP3;
    private javax.swing.JLabel lblP1;
    private javax.swing.JLabel lblP2;
    private javax.swing.JLabel lblP3;
    // End of variables declaration//GEN-END:variables
}
